spring.application.name=sensor-service
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
server.port=8082
# Fallback local settings
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:sensor_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
